name       : libcanberra
version    : 0.3
release    : 11
source     :
    - git|git://git.0pointer.net/libcanberra.git : c0620e432650e81062c1967cc669829dbd29b310
homepage   : http://0pointer.de/lennart/projects/libcanberra/
license    : LGPL-2.1-only
component  : desktop.library
summary    : XDG Sound Theme and Name implementation
description: |
    libcanberra is an implementation of the XDG Sound Theme and Name Specifications, for generating event sounds on free desktops, such as GNOME. It comes with several backends (ALSA, PulseAudio, OSS, GStreamer, null) and is designed to be portable
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gtk-doc)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libpulse)
    - pkgconfig(vorbis)
patterns   :
    - docs : /usr/share/doc
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-the-correct-freedesktop-sound-name.patch
    %autogen --disable-static \
               --enable-alsa \
               --enable-gtk2 \
               --enable-gtk3 \
               --enable-pulse \
               --with-builtin=dso \
               --disable-oss \
               --enable-gtk-doc \
               --enable-gtk-doc-html
build      : |
    %make -j1
install    : |
    %make_install -j1
